# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "mysql2"
gem "puma"
gem "puma_worker_killer", require: false
gem "sinatra"

# profiling and monitoring
gem "datadog_thread_tracer"
gem "ddtrace", ">= 1.0.0"
gem "dogstatsd-ruby"
gem "google-protobuf", "~> 3.0"
gem "newrelic_rpm"
gem "sentry-ruby"

group :development do
  gem "dotenv"
  gem "foreman"
end

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec-its"
end
