# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "ddtrace", ">= 1.0.0.beta1"
gem "mysql2"
gem "puma"
gem "puma_worker_killer", require: false
gem "sentry-ruby"
gem "sinatra"
gem "stackprof"

group :development do
  gem "dotenv"
  gem "foreman"
end

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec-its"
end
