name: webapp-ruby

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/webapp-ruby.yml"
      - "webapp/ruby/**"
    paths-ignore:
      - "**.md"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/workflows/webapp-ruby.yml"
      - "webapp/ruby/**"
    paths-ignore:
      - "**.md"

defaults:
  run:
    working-directory: webapp/ruby/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          working-directory: webapp/ruby/

      - run: bundle exec rspec

      - name: Slack Notification
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: test
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
